### ISSUE TITLE
Error presenting paywall: [Error: #3001 (wrongParam): AdaptyPaywall.viewConfiguration is nil]

### ISSUE THREAD

**Issue by huseyintamer** [adaptyteam/AdaptyUI-React-Native#15]
I’m encountering an issue when trying to use the new paywall builder with the following setup:

**Package.json**
```
"@adapty/react-native-ui": "^2.11.0",
"react-native-adapty": "^2.11.0"
```

**Code**
```
import React from 'react';
import {View, Text, StyleSheet, Button} from 'react-native';
import {createPaywallView} from '@adapty/react-native-ui';
import {adapty} from 'react-native-adapty';

const OnboardPaywall = ({route, navigation}) => {
  const presentPaywall = async () => {
    try {
      const locale = 'en';
      const id = 'paywal_general';
      const paywall = await adapty.getPaywall(id, locale);
      const view = await createPaywallView(paywall);
      view.registerEventHandlers(); // handle close press, etc
      await view.present();
    } catch (error) {
      console.log('Error presenting paywall:', error);
    }
  };

  return (
    <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
      <Text>Welcome to the Paywall Screen</Text>
      <Button title="Show Paywall" onPress={presentPaywall} />
    </View>
  );
};`
```

**Issue:**

While the old paywall builder works without any issues, the new paywall builder throws an error when attempting to present the paywall.

The error occurs when calling await view.present(); within the presentPaywall function.

```
 DEBUG  [2024-08-17T14:08:11.741Z] [adapty@2.11.0] "createController": Calling method: OK {"error": [Error: #3001 (wrongParam): AdaptyPaywall.viewConfiguration is nil]}
 ERROR  Error presenting paywall: [Error: #3001 (wrongParam): AdaptyPaywall.viewConfiguration is nil]
```

Steps to Reproduce:

	1.	Implement the provided code snippet in a React Native project.
	2.	Use the new paywall builder by calling the createPaywallView method.
	3.	Attempt to present the paywall using await view.present();.

**Comment by li4e** [comment]
Same problem

**Comment by li4e** [comment]
I figured out the issue. According to the [documentation](https://docs.adapty.io/v3.0/docs/migration-to-adapty-sdk-v3), the new Paywall Builder 3.0 is only supported by the new Adapty, AdaptyUI SDK versions 3.0.1. However, React Native Adapty uses the older versions. It seems we’ll have to wait for an update.

**Comment by li4e** [comment]
@huseyintamer, as a workaround, you can try using the legacy 2.0 paywall builder. It worked for me.

**Comment by huseyintamer** [comment]
@li4e Yes I already use legacy 2.0 paywall builder, it's worked. So waiting update to use New one. Thanks.

**Comment by troberts-28** [comment]
any movement on this?

**Comment by evlinH** [comment]
I contacted support on this issue. They told me to expect the release of the new SDK in September.

**Comment by troberts-28** [comment]
I also spoke to support about this and got an additional steer that it will be in late September 👍

**Comment by jadams777** [comment]
I have the same issue.

**Comment by vladd-g** [comment]
v3.0.0 is going to be out in early October

**Comment by chuanlol** [comment]
> v3.0.0 is going to be out in early October

is it getting delayed?

**Comment by vladd-g** [comment]
@chuanlol hopefully next week

**Comment by vladd-g** [comment]
@huseyintamer we understand the importance; the priority is very high

**Comment by ansh** [comment]
@vladd-g When is the new update coming out? It's been far too long.

**Comment by FurkanKayaDev** [comment]
@vladd-g Hello, any news? We are still waiting the update

**Comment by vladd-g** [comment]
hi @huseyintamer @li4e @troberts-28 @evlinH @jadams777 @chuanlol @ansh @FurkanKayaDev 

v3.0.0 is out!

**Comment by ansh** [comment]
Great! Thanks @vladd-g 

Unfortunately, I already migrated my apps to RevenueCat
