### ISSUE TITLE
Incompatible with v2.9.1 (latest) 

### ISSUE THREAD

**Issue by ansh** [adaptyteam/AdaptyUI-React-Native#2]
This package is incompatible with `react-native-adapty@2.9.1` which is the latest version.

It gives the following error: `CocoaPods could not find compatible versions for pod "Adapty"`

If I downgrade the package to `2.7.0` then it works. According to Discord this is a known issue.

When will this be fixed?

**Comment by vladd-g** [comment]
hi @ansh, working on it

**Comment by vladd-g** [comment]
@ansh approximately late Jan – early Feb

**Comment by hasanfd** [comment]
Hello,
Is there any update about this?

**Comment by ansh** [comment]
@vladd-g Hi! Is there any update now? Reaching out since this was the timeline I was given.

**Comment by vladd-g** [comment]
@hasanfd @ansh @StCyr please update to the `2.9.3` and `2.1.0` respectively

**Comment by russriser** [comment]
@vladd-g Thank you! 🙌

**Comment by hasanfd** [comment]
iOS is working. However, in android, I am getting this error on startup, 

`IllegalStateException: TypeToken must be created with a type argument: new TypeToken<...>() {}; When using code shrinkers (ProGuard, R8, ...) make sure that generic signatures are preserved.`

I am using proguard. So, I gave this config to proguard, 

`-keep class com.adapty.** { *; }
`

Is there any config you are aware that I should put for proguard?
