### ISSUE TITLE
Unable to build Android debug build

### ISSUE THREAD

**Issue by GaddiSunshine** [adaptyteam/AdaptyUI-React-Native#8]
Unable to build an android debug build with the package `"@adapty/react-native-ui": "2.0.1"`. Building a release build works.
When I remove the `@adapty/react-native-ui` package, then the build works.

Platform:
- Android

Versions:
```
"react-native": "0.72.6",
"expo": "49.0.18",
"react-native-adapty": "2.7.0",
"@adapty/react-native-ui": "2.0.1",
```

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find io.adapty.internal:crossplatform-ui:2.0.1.
     Searched in the following locations:
       - file:/Users/user/Documents/Smitten/app/client/node_modules/react-native-adapty/lib/android/localMaven/io/adapty/internal/crossplatform-ui/2.0.1/crossplatform-ui-2.0.1.pom
       - file:/Users/user/Documents/Smitten/app/client/node_modules/react-native/android/io/adapty/internal/crossplatform-ui/2.0.1/crossplatform-ui-2.0.1.pom
       - file:/Users/user/Documents/Smitten/app/client/node_modules/jsc-android/dist/io/adapty/internal/crossplatform-ui/2.0.1/crossplatform-ui-2.0.1.pom
       - https://dl.google.com/dl/android/maven2/io/adapty/internal/crossplatform-ui/2.0.1/crossplatform-ui-2.0.1.pom
       - https://repo.maven.apache.org/maven2/io/adapty/internal/crossplatform-ui/2.0.1/crossplatform-ui-2.0.1.pom
       - https://www.jitpack.io/io/adapty/internal/crossplatform-ui/2.0.1/crossplatform-ui-2.0.1.pom
       - https://oss.sonatype.org/content/repositories/snapshots/io/adapty/internal/crossplatform-ui/2.0.1/crossplatform-ui-2.0.1.pom
     Required by:
         project :app > project :adapty_react-native-ui
```

**Comment by GaddiSunshine** [comment]
> @GaddiSunshine now you can upgrade, we've just released `"react-native-adapty": "2.9.3"` and `"@adapty/react-native-ui": "2.1.0"`
> 
> The first path from the snippet provided is `file:/Users/user/Documents/Smitten/app/client/node_modules/react-native-adapty/lib/android/localMaven/io/adapty/internal/crossplatform-ui/2.0.1/crossplatform-ui-2.0.1.pom`, did you add it manually as `maven { ........ }`? If so, you can also add the missing one, where the `react-native-adapty/lib/` is replaced by `@adapty/react-native-ui/`

Thanks for the reply. I tried the new versions.

Versions:
```
"@adapty/react-native-ui": "2.1.0",
"expo": "49.0.18",
"react-native": "0.72.6",
"react-native-adapty": "2.9.3",
```

With these versions I still have the same problem:
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find io.adapty.internal:crossplatform-ui:2.1.1.
     Searched in the following locations:
       - file:/Users/gudmundurgardararnason/Documents/Smitten/app/client/node_modules/react-native-adapty/lib/android/localMaven/io/adapty/internal/crossplatform-ui/2.1.1/crossplatform-ui-2.1.1.pom
       - file:/Users/gudmundurgardararnason/Documents/Smitten/app/client/node_modules/react-native/android/io/adapty/internal/crossplatform-ui/2.1.1/crossplatform-ui-2.1.1.pom
       - file:/Users/gudmundurgardararnason/Documents/Smitten/app/client/node_modules/jsc-android/dist/io/adapty/internal/crossplatform-ui/2.1.1/crossplatform-ui-2.1.1.pom
       - https://dl.google.com/dl/android/maven2/io/adapty/internal/crossplatform-ui/2.1.1/crossplatform-ui-2.1.1.pom
       - https://repo.maven.apache.org/maven2/io/adapty/internal/crossplatform-ui/2.1.1/crossplatform-ui-2.1.1.pom
       - https://www.jitpack.io/io/adapty/internal/crossplatform-ui/2.1.1/crossplatform-ui-2.1.1.pom
       - https://oss.sonatype.org/content/repositories/snapshots/io/adapty/internal/crossplatform-ui/2.1.1/crossplatform-ui-2.1.1.pom
     Required by:
         project :app > project :adapty_react-native-ui
```


I have not added anything manually as the android folder is generated by expo in a managed workflow.

**Comment by vladd-g** [comment]
@GaddiSunshine could you please try the _Sync project with gradle files_ option with the Android project?

**Comment by GaddiSunshine** [comment]
> @GaddiSunshine could you please try the _Sync project with gradle files_ option with the Android project?

Hey @vladd-g I have tried cleaning, syncing, prebuilding, building and everything. When I have the @adapty/react-native-ui installed, I always get the same error when building an android debug build.

**Comment by GaddiSunshine** [comment]
> > @GaddiSunshine could you please try the _Sync project with gradle files_ option with the Android project?
> 
> Hey @vladd-g I have tried cleaning, syncing, prebuilding, building and everything. When I have the @adapty/react-native-ui installed, I always get the same error when building an android debug build.

I tried upgrading to the following packages:

```
"react-native": "0.73.4",
"expo": "50.0.7",
```

Still getting the same errors while trying to build android debug build.

**Comment by vladd-g** [comment]
@GaddiSunshine did you try [prebuilding](https://docs.expo.dev/workflow/prebuild/)?

But please be careful,
> If you manually modify the android or ios directory, you cannot re-run npx expo prebuild safely, as this may overwrite your changes.

As far as I can see, the expo is aware of custom maven path from the main Adapty SDK (the first path in the list in your snippet), but isn't aware of that from the AdaptyUI SDK. Looks like it needs rebuilding or something

**Comment by GaddiSunshine** [comment]
> @GaddiSunshine did you try [prebuilding](https://docs.expo.dev/workflow/prebuild/)?
> 
> But please be careful,
> 
> > If you manually modify the android or ios directory, you cannot re-run npx expo prebuild safely, as this may overwrite your changes.
> 
> As far as I can see, the expo is aware of custom maven path from the main Adapty SDK (the first path in the list in your snippet), but isn't aware of that from the AdaptyUI SDK. Looks like it needs rebuilding or something

Yes, I have tried prebuilding. I have removed and prebuilt/built the android folder again multiple times. I have done gradle clean and gradle sync. Nothing is working. Every time `@adapty/react-native-ui` is in my dependencies, I am unable to build. Always get the same error on android.

**Comment by vladd-g** [comment]
Well, as a temporary solution, you can add it manually to your android module's `build.gradle` (or `settings.gradle`, depending on your project settings, detailed info in the collapsed _The instruction on how to add it_ section [here](https://docs.adapty.io/docs/android-installation#install-via-gradle), but instead of `mavenCentral()` you need `maven { url 'RELATIVE_PATH_TO_NODE_MODULES/@adapty/react-native-ui/android/localMaven' }`)

**Comment by GaddiSunshine** [comment]
> Well, as a temporary solution, you can add it manually to your android module's `build.gradle` (or `settings.gradle`, depending on your project settings, detailed info in the collapsed _The instruction on how to add it_ section [here](https://docs.adapty.io/docs/android-installation#install-via-gradle), but instead of `mavenCentral()` you need `maven { url 'RELATIVE_PATH_TO_NODE_MODULES/@adapty/react-native-ui/android/localMaven' }`)

Hey @vladd-g Thanks for all the replies. It turned out to be a similar issue to [this one](https://github.com/adaptyteam/AdaptySDK-React-Native/issues/80). I was able to do [this](https://github.com/adaptyteam/AdaptySDK-React-Native/issues/80#issuecomment-1694675411) workaround. Now I am able to build and everything works as expected.

**Comment by vladd-g** [comment]
Hey @GaddiSunshine, happy to hear that! And thanks for sharing!

**Comment by vladd-g** [comment]
@GaddiSunshine also please update "react-native-adapty" to "2.9.6"
